name: pip_image
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  path_provider: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
       - images/icon/1.jpg
       - images/icon/2.jpg
       - images/icon/3.jpg
       - images/icon/4.jpg
       - images/icon/5.jpg
       - images/icon/6.jpg
       - images/icon/7.jpg
       - images/icon/8.jpg
       - images/icon/9.jpg
       - images/icon/10.jpg
       - images/icon/11.jpg
       - images/icon/12.jpg
       - images/icon/13.jpg

       - images/test.jpg
       - images/test1.jpeg

       - images/1/mask.png
       - images/1/frame.png
       - images/2/mask.png
       - images/2/frame.png
       - images/3/mask.png
       - images/3/frame.png
       - images/4/mask.png
       - images/4/frame.png
       - images/5/mask.png
       - images/5/frame.png
       - images/6/mask.png
       - images/6/frame.png
       - images/7/mask.png
       - images/7/frame.png
       - images/8/mask.png
       - images/8/frame.png
       - images/9/mask.png
       - images/9/frame.png
       - images/10/mask.png
       - images/10/frame.png
       - images/11/mask.png
       - images/11/frame.png
       - images/12/mask.png
       - images/12/frame.png
       - images/13/mask.png
       - images/13/frame.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
